
import { Customer } from "./types";

export const customers: Customer[] = [
  {
    id: "c-001",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    status: "active",
    lastActive: "2023-04-11",
    amount: 250.99,
    subscription: "Premium",
  },
  {
    id: "c-002",
    name: "Sarah Williams",
    email: "sarah.w@example.com",
    status: "active",
    lastActive: "2023-04-09",
    amount: 199.50,
    subscription: "Standard",
  },
  {
    id: "c-003",
    name: "Michael Brown",
    email: "michael.b@example.com",
    status: "inactive",
    lastActive: "2023-03-15",
    amount: 0,
    subscription: "Canceled",
  },
  {
    id: "c-004",
    name: "Emily Davis",
    email: "emily.davis@example.com",
    status: "active",
    lastActive: "2023-04-10",
    amount: 399.99,
    subscription: "Premium Plus",
  },
  {
    id: "c-005",
    name: "Robert Wilson",
    email: "robert.w@example.com",
    status: "pending",
    lastActive: "2023-04-05",
    amount: 0,
    subscription: "Trial",
  },
  {
    id: "c-006",
    name: "Jennifer Taylor",
    email: "jennifer.t@example.com",
    status: "active",
    lastActive: "2023-04-08",
    amount: 299.50,
    subscription: "Premium",
  },
  {
    id: "c-007",
    name: "David Martinez",
    email: "david.m@example.com",
    status: "inactive",
    lastActive: "2023-02-28",
    amount: 0,
    subscription: "Canceled",
  },
  {
    id: "c-008",
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    status: "active",
    lastActive: "2023-04-12",
    amount: 199.50,
    subscription: "Standard",
  },
  {
    id: "c-009",
    name: "James Thomas",
    email: "james.t@example.com",
    status: "pending",
    lastActive: "2023-04-07",
    amount: 0,
    subscription: "Trial",
  },
  {
    id: "c-010",
    name: "Jessica Robinson",
    email: "jessica.r@example.com",
    status: "active",
    lastActive: "2023-04-11",
    amount: 399.99,
    subscription: "Premium Plus",
  },
  {
    id: "c-011",
    name: "Daniel White",
    email: "daniel.w@example.com",
    status: "active",
    lastActive: "2023-04-10",
    amount: 250.99,
    subscription: "Premium",
  },
  {
    id: "c-012",
    name: "Amanda Clark",
    email: "amanda.c@example.com",
    status: "inactive",
    lastActive: "2023-03-01",
    amount: 0,
    subscription: "Canceled",
  },
  {
    id: "c-013",
    name: "Christopher Lee",
    email: "chris.lee@example.com",
    status: "active",
    lastActive: "2023-04-09",
    amount: 299.50,
    subscription: "Premium",
  },
  {
    id: "c-014",
    name: "Sophia Scott",
    email: "sophia.s@example.com",
    status: "pending",
    lastActive: "2023-04-06",
    amount: 0,
    subscription: "Trial",
  },
  {
    id: "c-015",
    name: "Matthew Green",
    email: "matthew.g@example.com",
    status: "active",
    lastActive: "2023-04-08",
    amount: 199.50,
    subscription: "Standard",
  },
  {
    id: "c-016",
    name: "Olivia Baker",
    email: "olivia.b@example.com",
    status: "active",
    lastActive: "2023-04-11",
    amount: 399.99,
    subscription: "Premium Plus",
  },
  {
    id: "c-017",
    name: "Andrew Nelson",
    email: "andrew.n@example.com",
    status: "inactive",
    lastActive: "2023-03-10",
    amount: 0,
    subscription: "Canceled",
  },
  {
    id: "c-018",
    name: "Emma Carter",
    email: "emma.c@example.com",
    status: "active",
    lastActive: "2023-04-12",
    amount: 250.99,
    subscription: "Premium",
  },
  {
    id: "c-019",
    name: "Joshua Phillips",
    email: "joshua.p@example.com",
    status: "pending",
    lastActive: "2023-04-05",
    amount: 0,
    subscription: "Trial",
  },
  {
    id: "c-020",
    name: "Megan Evans",
    email: "megan.e@example.com",
    status: "active",
    lastActive: "2023-04-10",
    amount: 199.50,
    subscription: "Standard",
  },
];
